apiVersion: v1
kind: Service
metadata:
  name: {{ include "prachi.fullname" . }}
  labels:
    {{- include "prachi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prachi.service.type }}
  ports:
    - port: {{ .Values.prachi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prachi.selectorLabels" . | nindent 4 }}
