{{- if .Values.prachi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prachi.serviceAccountName" . }}
  labels:
    {{- include "prachi.labels" . | nindent 4 }}
  {{- with .Values.prachi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
